redis:
  host: localhost
  port: 6379
  password: ""

database:
  host: localhost
  port: 3306
  name: rnkm-auth-db
  username: root
  password: root

app:
  port: 3002
  debug: true
  secret: <secret>

chula-sso:
  host: https://account.it.chula.ac.th
  app-id: <app id>
  app-secret: <app secret>

service:
  backend: localhost:3001

jwt:
  secret: <secret>
  expires_in: 3600
  issuer: https://rabnongkaomai.com